export const inputState = $state({
	searchContent: '',
	isSearching: true,
	hasSearched: false,
	lastSearch: '',
	aiInput: '',
	advancedSearch: false,
	id: '',
	ti: '',
	au: '',
	abs: '',
	co: '',
	jr: '',
	cat: '',
	rn: '',
	sortBy: 'Sort By',
	sortOrder: 'Sort Order',
	startIndex: 0,
	maxResults: 2,
	statusText: '',
	statusKeyword: ''
});
